// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SqlClientProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("SqlClientProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing SqlClientProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SqlClientProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "SqlClientProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing SqlClientProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
